apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  namespace: dp01-dev
  name: dp01
spec:
  license:
    accept: true
    license: L-RJON-CCCP46
    use: nonproduction
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 4Gi
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: admin-secret
  domains:
    - certs:
        - certType: usrcerts
          secret: booking-service-secret1
        - certType: usrcerts
          secret: booking-service-secret2
        - certType: usrcerts
          secret: booking-service-secret3
      dpApp:
        config:
          - booking-service-config
        local:
          - booking-service-local
      name: Booking
  version: 10.0-cd
  image: image-registry.openshift-image-registry.svc:5000/dp01-ns/dp01:0.0.1
  replicas: 1
